---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3060660488-l141O0jleXnNuTYlBY0mpW65CeXeKCrCn8nkjz3
:access_token_secret: 8KTji5rqxHkYAlFz6J9E01vsd4RsVFcAl1Mp0Nu3T9YY0
